import type { Client, TimelineEvent } from './types';

export const mockClient: Client = {
  id: 'james-whitfield',
  name: 'James Whitfield',
  tier: 'VIP',
  preferredBrands: ['Rolex', 'Patek Philippe', 'Audemars Piguet'],
  lifetimeValue: 384500,
  tradeInCount: 2,
  lastInteractionDate: '2026-05-28T10:00:00',
};

export const mockEvents: TimelineEvent[] = [
  {
    id: 'evt-1',
    type: 'appointment',
    date: '2026-05-28T10:00:00',
    title: 'In-person showroom visit — Nautilus 5711 allocation',
    body: 'Client attended a private viewing session. Discussed upcoming Patek Philippe Nautilus 5711 allocation. Client expressed strong intent to acquire and asked to be first on the list.',
    channel: 'in_person',
    handledBy: 'Sarah K.',
  },
  {
    id: 'evt-2',
    type: 'sourcing',
    date: '2026-05-10T15:20:00',
    title: 'Sourcing: Audemars Piguet Royal Oak Jumbo ref. 5402',
    body: 'Seller initiated a sourcing request on behalf of the client for a vintage Audemars Piguet Royal Oak Jumbo ref. 5402 (pre-1985). Client is open to grey-market sources.',
    channel: 'platform',
    handledBy: 'Sarah K.',
  },
  {
    id: 'evt-3',
    type: 'quotation',
    date: '2026-04-22T11:30:00',
    title: 'Quotation: Patek Philippe 5726A Annual Calendar',
    body: 'Formal quote sent for Patek Philippe 5726A Annual Calendar in stainless steel. Client had expressed interest after viewing the piece at Geneva Watch Days.',
    channel: 'email',
    handledBy: 'Sarah K.',
    value: 68000,
  },
  {
    id: 'evt-4',
    type: 'message',
    date: '2026-04-15T09:45:00',
    title: 'Client confirmed interest in the 5726A',
    body: 'Client replied via WhatsApp confirming strong interest in the Patek 5726A quotation. Asked about payment structure and whether part-exchange is possible.',
    channel: 'whatsapp',
    handledBy: 'Sarah K.',
  },
  {
    id: 'evt-5',
    type: 'purchase',
    date: '2026-03-18T14:00:00',
    title: 'Purchase: Rolex Daytona 116500LN',
    body: 'Client completed the purchase of a Rolex Daytona ref. 116500LN. Partial trade-in credit applied from Speedmaster. Full handover completed in-store.',
    channel: 'in_person',
    handledBy: 'Sarah K.',
    value: 42500,
  },
  {
    id: 'evt-6',
    type: 'trade_in',
    date: '2026-03-18T13:30:00',
    title: 'Trade-in: Omega Speedmaster Moonwatch',
    body: 'Client traded in an Omega Speedmaster Professional Moonwatch in excellent condition. Agreed value of £6,200 applied as part-exchange credit toward the Daytona purchase.',
    channel: 'in_person',
    handledBy: 'Sarah K.',
    value: 6200,
  },
  {
    id: 'evt-7',
    type: 'call',
    date: '2026-02-28T16:15:00',
    title: '20-min call — vintage interest and upcoming sourcing',
    body: 'Client mentioned interest in expanding into vintage pieces, specifically pre-1985 Heuer Carrera references. Expressed curiosity about ref. 2447. Follow-up sourcing agreed.',
    channel: 'phone',
    handledBy: 'Marcus T.',
  },
  {
    id: 'evt-8',
    type: 'email',
    date: '2026-02-10T09:00:00',
    title: 'Invite confirmed: Private Watch Showcase',
    body: "Initial outreach sent confirming client's attendance at a private watch showcase event. Client replied promptly with acceptance and a +1 guest request.",
    channel: 'email',
    handledBy: 'Marcus T.',
  },
];
