import type { Theme } from './themes';

type CssVarMap = Record<string, string>;

function flattenObject(obj: Record<string, unknown>, prefix: string): CssVarMap {
  const result: CssVarMap = {};
  for (const [key, value] of Object.entries(obj)) {
    const kebab = key.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`);
    const name  = `${prefix}-${kebab}`;
    if (Array.isArray(value)) {
      throw new Error(`flattenObject: array value at "${name}" is not supported`);
    }
    if (typeof value === 'object' && value !== null) {
      Object.assign(result, flattenObject(value as Record<string, unknown>, name));
    } else {
      result[name] = String(value);
    }
  }
  return result;
}

export function toCssVariables(theme: Theme, prefix = 'token'): CssVarMap {
  return flattenObject(theme as unknown as Record<string, unknown>, prefix);
}

function mapToCss(vars: CssVarMap, indent = '  '): string {
  return Object.entries(vars)
    .map(([key, value]) => `${indent}--${key}: ${value};`)
    .join('\n');
}

export function generateCss(input: { dark: Theme; light: Theme }): string {
  const darkVars  = toCssVariables(input.dark);
  const lightVars = toCssVariables(input.light);

  return [
    '/* @tokens-start — do not edit, generated by scripts/generate-tokens.ts */',
    ':root {',
    mapToCss(darkVars),
    '}',
    '',
    '[data-theme="light"] {',
    mapToCss(lightVars),
    '}',
    '/* @tokens-end */',
  ].join('\n');
}
